project:
  type: website
  execute-dir: project
  output-dir: docs
  render: 
    - "*.qmd"

execute: 
  freeze: auto

website:
  title: "LTER Network Documentation"
  repo-url: https://github.com/lter/docs-network
  repo-actions: [issue]
  favicon: images/logo_lter.png
  navbar:
    background: primary
    left:
      - text: "IMs"
        menu: 
          - text: "IM Home"
            href: im/home.qmd
          - text: "New to LTER"
            href: im/new-to-lter.qmd
          - text: "New to IM"
            href: im/new-to-im.qmd
          - text: "EML"
            href: im/eml.qmd
          - text: "GitHub Organizations"
            href: im/github-organization-recs.qmd
          - text: "Site Identifier"
            href: im/site-identifier.qmd
          - text: "Site Personnel"
            href: im/site-personnel.qmd
          - text: "Site Publications"
            href: im/site-publications.qmd
          - text: "Site Websites"
            href: im/site-websites.qmd
          - text: "Bibtex"
            href: im/bibtex.qmd
          - text: "Biblio Fields"
            href: im/biblio-fields.qmd
          - text: "Getting Help"
            href: im/getting-help.qmd
          - text: "Editing IM Docs"
            href: im/edits.qmd
    right: 
      - icon: github
        href: https://github.com/lter/docs-network
  page-footer: 
    center: "Copyright 2024, LTER Network"
    background: secondary

format:
  html:
    theme:
       light: _extensions/lter/lter_scss-theme/theme_lter-edu-light.scss
       dark: _extensions/lter/lter_scss-theme/theme_lter-edu-dark.scss
    mainfont: Open Sans
    toc: true
    link-external-newwindow: true
    link-external-icon: false

editor: source