project:
  type: website
  execute-dir: project
  output-dir: docs
  render: 
    - "*.qmd"

execute: 
  freeze: auto

website:
  title: "LTER Network Documentation"
  repo-url: https://github.com/lter/docs-network
  repo-actions: [issue]
  favicon: images/logo_lter.png
  navbar:
    background: primary
    left:
      - text: "IMs"
        menu: 
          - text: "Home"
            href: im/home.qmd
          - text: "New to LTER"
            href: im/new-to-lter.qmd
          - text: "New to IM"
            href: im/new-to-im.qmd
          - text: "Get Help"
            href: im/getting-help.qmd
          - text: "Update People"
            href: im/site-personnel.qmd
          - text: "Update Pubs"
            href: im/site-publications.qmd
          - text: "Websites"
            href: im/site-websites.qmd
          - text: "Write EML"
            href: im/eml.qmd
          - text: "Site GitHub Orgs"
            href: im/github-organization-recs.qmd
      - text: "PIs"
        menu: 
          - text: "Home"
            href: pi/home.qmd
      - text: "Education"
        menu: 
          - text: "Home"
            href: edu/home.qmd
          - text: "Activities"
            href: edu/activities.qmd
          - text: "REUs"
            href: edu/reu.qmd
          - text: "RETs"
            href: edu/ret.qmd
          - text: "Postcard Project"
            href: edu/postcard-project.qmd
          - text: "Data Nuggets"
            href: edu/data-nuggets.qmd
          - text: "Bylaws"
            href: edu/bylaws.qmd
          - text: "Resources"
            href: edu/resources.qmd
      - text: "Broadening Participation"
        menu: 
          - text: "Home"
            href: broaden_particip/home.qmd
      - text: "Grad"
        menu: 
          - text: "Home"
            href: grad/home.qmd
    right: 
      - text: "Editing This Site"
        href: general/edits.qmd
      - icon: github
        href: https://github.com/lter/docs-network
  page-footer: 
    center: "Copyright 2024, LTER Network"
    background: secondary

format:
  html:
    theme:
       light: _extensions/lter/lter_scss-theme/theme_lter-edu-light.scss
       dark: _extensions/lter/lter_scss-theme/theme_lter-edu-dark.scss
    mainfont: Open Sans
    toc: true
    link-external-newwindow: true
    link-external-icon: false

editor: source