---
title: "Home"
format: html
---

This website is the living home for shareable documentation and policies for the LTER Network. For more information about LTER, see [lternet.edu](https://lternet.edu/). There are several separate areas of documentation described below.

### [Information Managers](im/home.qmd) (IMs)

Every LTER site has an "information manager". These staff members are responsible for a variety of technical tasks at their respective sites, primarily centered around the management and archiving of the huge volumes of data produced by the long-term research performed at each site.

### [Principal Investigators](pi/home.qmd) (PI)

{{< fa person-digging >}}  _Under construction, check back later._

### [Education & Outreach Committee](edu/home.qmd) (EOC)

LTER recognizes the value of sustained interactions between students, teachers, and scientists, and strives to integrate LTER science with K-12 education. Most LTER sites conduct individual programs at the local level, and the network supports centralized approaches to educational initiatives where possible.

### [Broadening Participation Committee](broaden_particip/home.qmd)

{{< fa person-digging >}}  _Under construction, check back later._

### [Graduate Student Committee](grad/home.qmd) (GSC)

The graduate student committee is composed of one or more representatives from each LTER site who help to maintain a sense of community and connection among students at LTER sites. Grad Reps are servant-leaders who help communicate student issues and perspectives to faculty and staff and vice-versa. The information in these documents will help new graduate student representatives to get oriented to the role and expectations.

### [Committee Chairs](committee-chairs/home.qmd)

LTER committees and interest groups are run by volunteer members of the network, with logistical and (occasional) financial support from the LTER Network Office. Each committee operates a little differently to accommodate the needs and interest of members, but there are a few common activities and responsibilities that we lay out here.
