---
title: "Site Websites"
format: html
---

If you're one of those (un)lucky IMs who handles your LTER site's website, then read on.

## Content

Consistent with LTER's generally bottom-up philosophy, the content and organization of LTER site websites is not determined by the Network Office. Each site has different audiences to prioritize and is situated differently within its home institution (or within a group of institutions and partners). However, maintaining some consistency across sites allows NSF, reviewers, and colleagues to easily find the information that is important to them. To achieve this balance, the network developed and approved a set of [Content Guidelines for LTER websites](https://lternet.edu/?taxonomy=document-types&term=lter-network-branding). Please refer to these guidelines when developing new sites and updating existing websites. 

## Platforms

Exactly _how_ you go about creating or maintaining your site's website depends on the legacy of the existing website (if any), what resources are available to you at your institution, how much your site has budgeted for website work, and what your site needs from your website. Some of the more common options across sites are listed below, as well as one new and interesting option.

### Drupal and DEIMS

[Drupal](https://www.drupal.org/) is an open-source content management system for building and maintaining websites. Several LTER sites use Drupal, and some of them joined forces to create DEIMS (the Drupal Ecological Information Management System), a Drupal-based website solution which handles functionality common across LTER sites such as data catalog, bibliography, and personnel lists.

DEIMS was developed in Drupal 7 and upgrade instructions to Drupal 8/9 can be found in a [GitHub repository](https://github.com/lter/Deims7-8-Migration). Drupal manages information in a database, and modules have been developed to import and export ecological metadata language (EML) documents.
Developing a new website in Drupal is more complex than, e.g., WordPress, but offers more opportunities for customization. However, IM-supporting developments at EDI and the IMC have been replacing most functionality Drupal has been lauded for. If you already use DEIMS or are familiar with Drupal reach out to the IMs at these sites to learn more: [NTL](https://lter.limnology.wisc.edu/), [KNZ](http://knz.lternet.edu/), [PIE](https://pie-lter.ecosystems.mbl.edu/).

### WordPress

Many sites use WordPress for its ease of migration and editing. However, a DEIMS-like solution doesn't exist for WordPress, so you will have to find a way to support interactive features such as a data catalog. Reach out to the IMs at these sites to learn more: [VCR](https://www.vcrlter.virginia.edu/home2/), [CAP](https://sustainability-innovation.asu.edu/caplter/), [JRN](https://lter.jornada.nmsu.edu/).

### Static Website

There are many [advantages to static websites](https://blog.squido.org/why-static-html/). For example, you can typically find a free host for a static website, they're secure, and they can be blazingly fast. While static websites used to be just for geeks, content management systems are evolving which make the editing experience more similar to WordPress or Drupal. By harnessing the power of online services and APIs, static sites can include interactive features like data catalogs and bibliographies. Reach out to the IMs at these sites to learn more: [BLE](https://ble.lternet.edu/), [SBC](https://sbclter.msi.ucsb.edu/).

### DataONE Portal

For a relatively new paid option with simpler sites, you may be interested in [DataONE Portals](https://www.dataone.org/portals-tutorial/).  From DataONE:

> A portal is a collection of DataONE member node data packages on a unique webpage.

In other words, you can describe your project on your own portal page, and you can have a complete data catalog as long as all of your datasets are discoverable within DataONE.
If you need other fancy features though, you may need to look elsewhere.

### RSS Feeds from the Network Office
RSS feeds from the Network Office can provide an easy source of updated content and also help keep your site personnel up-to-date on network happenings. Both Drupal and Wordpress have quick and easy ways to display an rss feed. If you're not familiar, reach out to the Network Office. 
-  Announcements: https://lternet.edu/story_types/announcement/feedThis includes new Network-level programs (site exchanges, synthesis RFPs, etc.), as well as occasional announcements about LTER-relevant programs from partner networks and individual sites that are available broadly.
-  Featured Events: https://lternet.edu/events/tags/featured/feed/This includes our monthly LTER community calls (March and April will focus on progress in our currently-funded synthesis groups) as well as other committee-organized events such as the grad-organized lightning talks.  
-  News Stories: https://lternet.edu/stories/feed/ 
(for all stories) or there are variations for specific story-types: https://lternet.edu/story_types/education/feed or   https://lternet.edu/story_types/research/feed

In addition to the featured events rss feed noted above, individuals subscribe to the full calendar feed at https://lternet.edu/events.ics. Instructions for google calendar users [are here](https://wp-events-plugin.com/documentation/event-ical-feeds/#example-subscribing-to-events-using-google-calendar). 
