---
title: "Grad Committee Duties"
---

*Updated June 2025*

As LTER graduate student representatives, we are expected to fulfill specific duties to provide graduate students with the information, opportunities, and representation necessary to work successfully at each site. Since each site is unique, duties and responsibilities will differ, but certain duties should be fulfilled across sites. 

Below is a list of duties and descriptions that every graduate student representative should aspire to fulfill. ***Certain items may not be relevant to all sites or graduate student representatives.***

*  Graduate student representatives are encouraged to attend executive committee meetings for their site. We understand that each site is different, but as graduate student representatives we believe that we should have the opportunity to have direct conversations with the Executive Committee of our sites.

*  Create a staff-grad student liaison that acts as a middle person between graduate student representative and site director(s). The staff liaison could be the head field/lab tech for a site, site coordinator, or safety manager. This is not a requirement for all sites but could be useful at sites where there is little or no direct interaction between the graduate student representative and the site directors.

*  Graduate student representatives should be in touch with graduate students at their site so that they are aware of any issues that need to get addressed. This could be done by:
    *  Leading a site-specific climate survey once a year (ideally at the end of the field season, if applicable) to gauge how graduate students involved in the LTER feel about the current state of the site. A climate survey will be provided if this is the preferred method of communication. The results of the climate survey will be shared with the site director(s) to address any concerns at the site as well as the LTER GSC as a whole (when applicable).
    *  Encouraging students at their sites to fill out any network-wide surveys that the LTER distributes.
    *  Regular graduate student meetings or graduate student social events (anything that allows for regular communication between graduate students and the site representative).

*  If not already being managed by another person (such as an IM or administrator), the graduate student representatives should manage and update the site-specific grad student listserv (and other site communication channels) to make sure contacts are up-to-date. When the list is managed by another person, the graduate student representative should still be in communication with them to make sure the list stays current.

*  Graduate student representatives should communicate GSC meeting notes (can send link to notes document) and/or highlights to graduate students at each site so that all LTER-affiliated graduate students are aware of network-wide information and the presence of the GSC. 

*  During the site’s All-Hands-Meetings (or another applicable time, if a site does not have one), graduate student representatives should facilitate a graduate student session/social. If applicable, the graduate student representative will also manage other site-specific student needs such as managing visiting student housing.

*  New graduate student representatives will attend an orientation meeting with the GSC co-chairs and should familiarize themselves with the GSC orientation package, which consists of 1) orientation checklist document, 2) orientation to GSC document, 3) graduate student representative duties document (this document), and 4) GSC by-laws document.

*  Graduate student representatives will join one of the GSC working groups. Currently, the working groups are: community (works on GSC documentation), social media (manages the Instagram and SSALTER blog), and events and initiatives (coordinates network-wide graduate student events).

*  Some sites have two graduate students serving as co-representatives, an option that is open to all sites. This can be useful in multiple situations, such as one in which there are two primary institutions with many students/scientists at the site, or many institutions that are geographically spread out. It may be convenient to have one rep who lives near the site who is responsible for “site-specific” tasks (e.g., organizing in-person events or workshops with students) and another rep who lives farther away and is responsible for “network-specific” tasks (e.g., attending monthly GSC meetings and participating in working groups). You may also opt to have a co-rep during a transition period (however long you choose) so that the old rep can train the new one before stepping down. Whatever you decide, you should keep the co-chairs updated on your situation.

*  Each graduate student representative will coordinate one SSALTER blog post per academic year for their site. During the summer, they will identify at least one student who is willing and able to write the post in the upcoming fall or spring semester. Representatives are responsible for maintaining communication and ensuring the post is completed.
