---
title: "Graduate Student Committee Home"
format: html
---

The graduate student committee is composed of one or more representatives from each LTER site who help to maintain a sense of community and connection among students at LTER sites. Grad Reps are servant-leaders who help communicate student issues and perspectives to faculty and staff and vice-versa. The information in this manual will help new graduate student representatives to get oriented to the role and expectations.

## Mission and Goals

The mission of the Graduate Student Committee is to *Build graduate student networks between and within LTER sites to provide support for student collaboration, funding, and inclusion.*

Graduate representatives aim to:

1.  Create an inclusive and supportive community to foster dialogue and collaboration among graduate student researchers

    -   Regional meetings within and across sites
    -   Meet-up at annual conferences such as AGU, ESA, etc.
    -   Sister sites - find institutions or sites that are close/associated and host tours and research presentation/discussions

2.  Provide a resource for professional development and networking

    -   Reach out to LTER alumni who work in various different fields after grad school

    -   Host webinar/local events that are aimed at providing current students with knowledge, resources, and support

    -   Regular emails that contain fellowships, workshops, postdoc positions, research initiatives, etc..

3.  Serve as a liaison between graduate students and PIs

    -   Increased transparency between PIs and graduate students

    -   Graduate students should be more involved in site review to better understand the logistic and administrative components of the LTERs


## Orientation

### History of the LTER Network

In 1980, the National Science Foundation funded the first Long-Term Ecological Research (LTER) sites to provide a longer view on ecological processes. Today, research programs at 27 LTER sites support ecological discovery on the influence of long-term and large-scale phenomenon. LTER sites also serve the wider ecological community by:

*  Making more than 40 years of sustained observations publicly available
*  Developing and maintaining large-scale experiments, which provide starting conditions for process-level studies and help to parameterize and test models for conditions that may not currently exist
*  Providing long-term context and deep knowledge of place for researchers working on shorter-term projects training hundreds of graduate students in interdisciplinary and collaborative team science

Each LTER site involves dozens of researchers, typically including microbial, community, and landscape ecologists, but also hydrologists, geochemists, social scientists, economists and even artists, historians, or philosophers. The shared knowledge of place offers unusual common ground for exploring disciplinary intersections.

If you are new to the LTER Network you can watch the [LTER Network Orientation Video](https://youtu.be/whPMsFWBTX8?si=I3PqA41Rn2Y_LFFw) and check out the "[New to the Network](https://lternet.edu/new-to-the-network/)" web page. For more about how the LTER Network is organized and governed, see [network organization](https://lternet.edu/network-organization/).

To keep up with network-wide activities:

- [ ] [Subscribe to the Network News](https://us12.campaign-archive.com/home/?u=d7494403ed9d8c97a5479f0d4&id=51157f4ed5)
- [ ] Follow the LTER Network on [Bluesky](https://bsky.app/profile/uslter.bsky.social) and [LinkedIn](https://www.linkedin.com/company/lter-network/)

## The Graduate Student Committee

The LTER GSC was established to foster interaction among graduate students working at LTER sites and between students and senior LTER scientists to create student opportunities for intersite research and to develop interdisciplinary graduate training programs.

Check out the [website](https://lternet.edu/committees/graduate-student/), [Facebook](http://www.facebook.com/groups/LTER.graduate/), [Instagram](http://www.instagram.com/lter_community/?hl=en), and [Short Stoies About Long Term Research (SSALTER) blog](http://lternet.edu/SSALTER)!

What does a grad rep do?
As a graduate student representative the two basic requirements are to attend monthly committee meetings and act as a leader and liaison for graduate students at their site. In addition to monthly meetings, the GSC stays connected through email, Slack, and Google Drive (please contact the committee co-chairs to enable access to these platforms). 

Please make sure to read over the mission statement and bylaws. 

### People to Know

The GSC Co-Chairs are your immediate contact for questions and communication related to the committee and associated activities. The current co-chairs are:

*  Eamon Hennessy (she/her, ehenness@cougarnet.uh.edu)
*  Joey Krieger Lodge (they/them, joey.lodge@colorado.edu)

The GSC often works closely with staff at the LTER Network office who help fund and organize grad student events and provide advice and support as needed for the GSC Committee and LTER grad students more broadly.

*  Marty Downs (she/her), Director of the LTER Network Office, provides support for the committee, particularly in regards to funding allocation and network-wide considerations. She can be reached at downs@nceas.ucsb.edu.

*  Gabriel De La Rosa (he/him), LTER Communications Coordinator, was the direct liaison to the GSC and often attended committee meetings until his position was cut due to funding in September 2025.

### GSC-Funded Projects and Events

The LTER Network Office accepts proposals for meetings and events to foster cross-site student collaboration, networking, and skill acquisition. Such events may include regional meetings between multiple LTER sites, cross-site experiments, data sharing, and seminar series. The GSC also helps promote and disseminate network-wide opportunities for graduate students and other early career researchers.

### Orientation Checklist

- [ ] Added to grad-rep@lternet.edu listserv
- [ ] Added to shared Google drive
- [ ] Access to shared GSC Drive from non-Google emails
- [ ] Added to GSC slack (or link to join sent)
- [ ] Read the orientation documents (this website)
- [ ] Check in about Pro Deals. Do you need to send an updated list to Gabe De La Rosa?
- [ ] Check in about the SSALTER blog. Is your site currently up?
- [ ] Check in about the @lter_community Instagram
- [ ] Decide which working group you are interested in being a part of:

  *  **Community working group**: ensures that committee documents are up to date and creates documentation when needed.
  *  **Social media working group**: facilitates digital media interactions between LTER sites by sharing experiences through managing a blog and overseeing the LTER Instagram account.
  *  **Events & initiatives working group**: develops and organizes events across the LTER network with a focus on catering to graduate student interests and needs.
  *  Put your name in the working group you decide to join here: [LTER GSC Working Groups](https://docs.google.com/spreadsheets/u/1/d/1VDvIuGzn3JKvrGfaMdnpcLbJ5nzZFkZE_kqa0MJw1Ok/edit?usp=drive_web&ouid=107222726819450778613)

- [ ] Notify LNO of committee changes
- [ ] The new rep and the rep stepping down will attend the new rep’s first meeting together. The rep stepping down is expected to introduce the new rep to the committee and assist with any questions the new rep may have during their first meeting.

## Duties

*Updated June 2025*

As LTER graduate student representatives, we are expected to fulfill specific duties to provide graduate students with the information, opportunities, and representation necessary to work successfully at each site. Since each site is unique, duties and responsibilities will differ, but certain duties should be fulfilled across sites. 

Below is a list of duties and descriptions that every graduate student representative should aspire to fulfill. ***Certain items may not be relevant to all sites or graduate student representatives.***

*  Graduate student representatives are encouraged to attend executive committee meetings for their site. We understand that each site is different, but as graduate student representatives we believe that we should have the opportunity to have direct conversations with the Executive Committee of our sites.

*  Create a staff-grad student liaison that acts as a middle person between graduate student representative and site director(s). The staff liaison could be the head field/lab tech for a site, site coordinator, or safety manager. This is not a requirement for all sites but could be useful at sites where there is little or no direct interaction between the graduate student representative and the site directors.

*  Graduate student representatives should be in touch with graduate students at their site so that they are aware of any issues that need to get addressed. This could be done by:
    *  Leading a site-specific climate survey once a year (ideally at the end of the field season, if applicable) to gauge how graduate students involved in the LTER feel about the current state of the site. A climate survey will be provided if this is the preferred method of communication. The results of the climate survey will be shared with the site director(s) to address any concerns at the site as well as the LTER GSC as a whole (when applicable).
    *  Encouraging students at their sites to fill out any network-wide surveys that the LTER distributes.
    *  Regular graduate student meetings or graduate student social events (anything that allows for regular communication between graduate students and the site representative).

*  If not already being managed by another person (such as an IM or administrator), the graduate student representatives should manage and update the site-specific grad student listserv (and other site communication channels) to make sure contacts are up-to-date. When the list is managed by another person, the graduate student representative should still be in communication with them to make sure the list stays current.

*  Graduate student representatives should communicate GSC meeting notes (can send link to notes document) and/or highlights to graduate students at each site so that all LTER-affiliated graduate students are aware of network-wide information and the presence of the GSC. 

*  During the site’s All-Hands-Meetings (or another applicable time, if a site does not have one), graduate student representatives should facilitate a graduate student session/social. If applicable, the graduate student representative will also manage other site-specific student needs such as managing visiting student housing.

*  New graduate student representatives will attend an orientation meeting with the GSC co-chairs and should familiarize themselves with the GSC orientation package, which consists of 1) orientation checklist document, 2) orientation to GSC document, 3) graduate student representative duties document (this document), and 4) GSC by-laws document.

*  Graduate student representatives will join one of the GSC working groups. Currently, the working groups are: community (works on GSC documentation), social media (manages the Instagram and SSALTER blog), and events and initiatives (coordinates network-wide graduate student events).

*  Some sites have two graduate students serving as co-representatives, an option that is open to all sites. This can be useful in multiple situations, such as one in which there are two primary institutions with many students/scientists at the site, or many institutions that are geographically spread out. It may be convenient to have one rep who lives near the site who is responsible for “site-specific” tasks (e.g., organizing in-person events or workshops with students) and another rep who lives farther away and is responsible for “network-specific” tasks (e.g., attending monthly GSC meetings and participating in working groups). You may also opt to have a co-rep during a transition period (however long you choose) so that the old rep can train the new one before stepping down. Whatever you decide, you should keep the co-chairs updated on your situation.

*  Each graduate student representative will coordinate one SSALTER blog post per academic year for their site. During the summer, they will identify at least one student who is willing and able to write the post in the upcoming fall or spring semester. Representatives are responsible for maintaining communication and ensuring the post is completed.

## Working Group Descriptions and Responsibilities


The leader(s) of each working group is expected to record notes in a meeting document and communicate to greater GSC if there are updates that need to be communicated to graduate students at all sites.

As of September 20205, the following working groups are active:

*  **Community Working Group**: ensures that committee documents are up to date and creates documentation when needed.

*  **Social Media Working Group**: facilitates digital media interactions between LTER sites by sharing experiences through managing a blog and overseeing the LTER Instagram account.

*  **Events & Initiatives Working Group**: develops and organizes events across the LTER network with a focus on meeting graduate student interests and needs.


## [Bylaws](bylaws.qmd)