---
title: "LTER Graduate Student Representatives Mission Statement and Goals"
format: html
---

*Building graduate student networks between and within LTER sites to provide support for student collaboration, funding, and inclusion.*

Graduate representatives aim to:

1.  Create an inclusive and supportive community to foster dialogue and collaboration among graduate student researchers

    -   Regional meetings within and across sites
    -   Meet-up at annual conferences such as AGU, ESA, etc.
    -   Sister sites - find institutions or sites that are close/associated and host tours and research presentation/discussions

2.  Provide a resource for professional development and networking

    -   Reach out to LTER alumni who work in various different fields after grad school

    -   Host webinar/local events that are aimed at providing current students with knowledge, resources, and support

    -   Regular emails that contain fellowships, workshops, postdoc positions, research initiatives, etc. 

3.  Serve as a liaison between graduate students and PIs

    -   Increased transparency between PIs and graduate students

    -   Graduate students should be more involved in site review to better understand the logistic and administrative components of the LTERs
