---
title: "LTER Graduate Student Representative Orientation"
format: html
---

*Updated June 2024*

## History of the LTER Network

In 1980, the National Science Foundation funded the first Long-Term Ecological Research (LTER) sites to provide a longer view on ecological processes. Today, research programs at 27 LTER sites support ecological discovery on the influence of long-term and large-scale phenomenon. LTER sites also serve the wider ecological community by:

*  Making more than 40 years of sustained observations publicly available
*  Developing and maintaining large-scale experiments, which provide starting conditions for process-level studies and help to parameterize and test models for conditions that may not currently exist
*  Providing long-term context and deep knowledge of place for researchers working on shorter-term projects training hundreds of graduate students in interdisciplinary and collaborative team science

Each LTER site involves dozens of researchers, typically including microbial, community, and landscape ecologists, but also hydrologists, geochemists, social scientists, economists and even artists, historians, or philosophers. The shared knowledge of place offers unusual common ground for exploring disciplinary intersections.

If you are new to the LTER Network you can watch the [LTER Network Orientation Video](https://youtu.be/whPMsFWBTX8?si=I3PqA41Rn2Y_LFFw) and check out the "[New to the Network](https://lternet.edu/new-to-the-network/)" web page. For more about how the LTER Network is organized and governed, see [network organization](https://lternet.edu/network-organization/).

To keep up with network-wide activities:

- [ ] [Subscribe to the Network News](https://us12.campaign-archive.com/home/?u=d7494403ed9d8c97a5479f0d4&id=51157f4ed5)
- [ ] Follow the LTER Network on [Bluesky](https://bsky.app/profile/uslter.bsky.social) and [LinkedIn](https://www.linkedin.com/company/lter-network/)

## The Graduate Student Committee

The LTER GSC was established to foster interaction among graduate students working at LTER sites and between students and senior LTER scientists to create student opportunities for intersite research and to develop interdisciplinary graduate training programs.

Check out the [website](https://lternet.edu/committees/graduate-student/), [Facebook](http://www.facebook.com/groups/LTER.graduate/), [Instagram](http://www.instagram.com/lter_community/?hl=en), and [Short Stoies About Long Term Research (SSALTER) blog](http://lternet.edu/SSALTER)!

What does a grad rep do?
As a graduate student representative the two basic requirements are to attend monthly committee meetings and act as a leader and liaison for graduate students at their site. In addition to monthly meetings, the GSC stays connected through email, Slack, and Google Drive (please contact the committee co-chairs to enable access to these platforms). 

Please make sure to read over the mission statement and bylaws. 

## People to Know

The GSC Co-Chairs are your immediate contact for questions and communication related to the committee and associated activities. The current co-chairs are:

*  Eamon Hennessy (she/her, ehenness@cougarnet.uh.edu)
*  Joey Krieger Lodge (they/them, joey.lodge@colorado.edu)

The GSC often works closely with staff at the LTER Network office who help fund and organize grad student events and provide advice and support as needed for the GSC Committee and LTER grad students more broadly.

*  Marty Downs (she/her), Director of the LTER Network Office, provides support for the committee, particularly in regards to funding allocation and network-wide considerations. She can be reached at downs@nceas.ucsb.edu.

*  Gabriel De La Rosa (he/him), LTER Communications Coordinator, was the direct liaison to the GSC and often attended committee meetings until his position was cut due to funding in September 2025.

## GSC-Funded Projects and Events

The LTER Network Office accepts proposals for meetings and events to foster cross-site student collaboration, networking, and skill acquisition. Such events may include regional meetings between multiple LTER sites, cross-site experiments, data sharing, and seminar series. The GSC also helps promote and disseminate network-wide opportunities for graduate students and other early career researchers.

## Orientation Checklist

- [ ] Added to grad-rep@lternet.edu listserv
- [ ] Added to shared Google drive
- [ ] Access to shared GSC Drive from non-Google emails
- [ ] Added to GSC slack (or link to join sent)
- [ ] Read the orientation documents (this website)
- [ ] Check in about Pro Deals. Do you need to send an updated list to Gabe De La Rosa?
- [ ] Check in about the SSALTER blog. Is your site currently up?
- [ ] Check in about the @lter_community Instagram
- [ ] Decide which working group you are interested in being a part of:

  *  **Community working group**: ensures that committee documents are up to date and creates documentation when needed.
  *  **Social media working group**: facilitates digital media interactions between LTER sites by sharing experiences through managing a blog and overseeing the LTER Instagram account.
  *  **Events & initiatives working group**: develops and organizes events across the LTER network with a focus on catering to graduate student interests and needs.
  *  Put your name in the working group you decide to join here: [LTER GSC Working Groups](https://docs.google.com/spreadsheets/u/1/d/1VDvIuGzn3JKvrGfaMdnpcLbJ5nzZFkZE_kqa0MJw1Ok/edit?usp=drive_web&ouid=107222726819450778613)

- [ ] Notify LNO of committee changes
- [ ] The new rep and the rep stepping down will attend the new rep’s first meeting together. The rep stepping down is expected to introduce the new rep to the committee and assist with any questions the new rep may have during their first meeting.