---
title: "EOC Activities"
---

## Approaches to Site Activities

Individual sites approach their education, outreach, and engagement activities in different ways, depending on their audiences, individual capacities, and local or national partners. Until 2023, the National Science Foundation required a certain amount of LTER funds be devoted to "Schoolyard LTERs" (i.e. specifically K-12 education activities). In 2023, the solicitation was changed to accommodate a wider range of engagement activities, which might include other informal science learning, art-science, or engagement with resource managers and users. 

Some sites choose to fund a portion of a staff member to work on education, outreach, or engagement activities. Others devote resources to working with a partner who is already embedded in the community. (Examples include Mass Audubon at the Plum Island LTER and the Asombro Institute at Jornada LTER or the Birch Aquarium at California Current Ecosystem LTER.)

Many education activities are necessarily hands-on and do not have a network-level component. Examples include:

- Site tours
- Hands-on classroom activities
- Site-level stakeholder engagement
- Individual Research Experiences for Undergraduates and/or Research Experiences for Teachers

The value of the network can be seen in two major ways. As a community-of-practice, interacting with other LTER network educators can generate creative new ideas and can improve the quality of the work done at individual sites. Other times, individual site educators can join forces to create a project that really is greater than the sume of the parts. Cross-site REU and RET professional development, site-to-site postcards, and [Data Nuggets](https://datanuggets.org/) all fit that description.
