---
title: "Education & Outreach Committee (EOC) Home"
format: html
---

LTER recognizes the value of sustained interactions between students, teachers, and scientists, and strives to integrate LTER science with K-12 education. Most LTER sites conduct individual programs at the local level, and the network supports centralized approaches to educational initiatives where possible.

Committee membership is identified by sites (at least 1 representative per site). Meetings are scheduled monthly and attendance is voluntary and dependent on individual members’ schedules and availability.

## Education/Outreach goals include:
- Utilizing LTER resources to enhance hands-on science learning for students
- Developing long-term research sites on or near school yards
- Facilitating communication between LTER scientists, formal and informal science educators, and school teachers
- Helping ecology education make best use of long-term studies
- Fostering understanding of the Earth’s ecosystems, including local ones
- Promoting outdoor, inquiry-based learning
- Stimulating interdisciplinary, collaborative science learning
- Integrating long-term and multi-factorial studies into education reform
- Promoting broad understanding of long-term ecological processes and the earth’s ecosystem

## Schedule and Organization

- The committee meets the first Thursday of each month at noon Pacific Time (1:00 MT / 2:00 CT / 3:00 ET). Committee members generally receive a calendar invitation via their google group membership. If you do not have a meeting invitation or need to access the meeting URL, it can be found in the [latest running notes](https://docs.google.com/document/d/1_D1FnCzTofZ6q4r4LxFbrkNbrSQNHERG9o9ZGDsQZ3o/edit?tab=t.0) document in the [shared google drive](https://drive.google.com/drive/u/0/folders/0AHiFZma83lhlUk9PVA).
- **Email list**: Outside of meetings, communication takes place on the google group email discussion list (education@lternet.edu). All members can (and should) feel free to post questions, resources, events, etc. If you would like to request access from an email that is not your work address, request to add that email from [the group's "About" page](https://groups.google.com/a/lternet.edu/g/education/about).
- **Shared Drive**: Active files are stored on the [LTER-committee-education](https://drive.google.com/drive/u/0/folders/0AHiFZma83lhlUk9PVA) shared google drive. All members in the google group have edit access to the shared drive. Unlike individual google drives, shared drives allow editors to delete or change content for all members. This makes it easier to keep the drive organized, but required some caution.
-  **Web Page**: The Committee has [a page](https://lternet.edu/committees/education/) on the network web site. Keeping content updated is a shared responsibility between the committee and the Network Office. Only the Network Office has edit access to the website, but fresh content from the committee is always appreciated.

## Approaches to Site Activities

Individual sites approach their education, outreach, and engagement activities in different ways, depedning on their audiences, individual capacities, and local or national partners. Until 2023, the National Science Foundation required a certain amount of LTER funds be devoted to "Schoolyard LTERs" (i.e. specifically K-12 education activities). In 2023, the solicitation was changed to accommodate a wider range of engagement activities, which might inlcude other informal science learning, art-science, or engagement with resource managers and users. 

Some sites choose to fund a portion of a staff member to work on education, outreach, or engagement activities. Others devote resources to working with a partner who is already embedded in the community. (Examples include Mass Audubon at the Plum Island LTER and the Asombro Institute at Jornada LTER.)


